from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    username = db.Column(db.String(80), nullable=False)
    password = db.Column(db.String(200), nullable=False)  # Store hashed passwords

class Transaction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    transaction_id = db.Column(db.String(50))
    timestamp = db.Column(db.String(50))
    card_number = db.Column(db.String(50))
    transaction_type = db.Column(db.String(50))
    retract = db.Column(db.String(10))
    no_notes_dispensed = db.Column(db.String(10))
    notes_dispensed_unknown = db.Column(db.String(10))
    amount = db.Column(db.String(50))
    response_code = db.Column(db.String(10))
    authentication = db.Column(db.Boolean)
    pin_entry = db.Column(db.Boolean)
    notes_dispensed = db.Column(db.String(50))
    notes_dispensed_count = db.Column(db.String(10))
    notes_dispensed_t1 = db.Column(db.String(10))
    notes_dispensed_t2 = db.Column(db.String(10))
    notes_dispensed_t3 = db.Column(db.String(10))
    notes_dispensed_t4 = db.Column(db.String(10))
    dispensed_t1 = db.Column(db.String(10))
    dispensed_t2 = db.Column(db.String(10))
    dispensed_t3 = db.Column(db.String(10))
    dispensed_t4 = db.Column(db.String(10))
    status = db.Column(db.String(50))
    stan = db.Column(db.String(50))
    terminal = db.Column(db.String(50))
    account_number = db.Column(db.String(50))
    transaction_number = db.Column(db.String(50))
    cash_dispensed = db.Column(db.String(50))
    cash_rejected = db.Column(db.String(50))
    cash_remaining = db.Column(db.String(50))
    number_of_total_inserted_notes = db.Column(db.Integer)
    note_count_bdt500 = db.Column(db.Integer)
    note_count_bdt1000 = db.Column(db.Integer)
    bdt500_abox = db.Column(db.Integer)
    bdt500_type1 = db.Column(db.Integer)
    bdt500_type2 = db.Column(db.Integer)
    bdt500_type3 = db.Column(db.Integer)
    bdt500_type4 = db.Column(db.Integer)
    bdt500_retract = db.Column(db.Integer)
    bdt500_reject = db.Column(db.Integer)
    bdt500_retract2 = db.Column(db.Integer)
    bdt1000_abox = db.Column(db.Integer)
    bdt1000_type1 = db.Column(db.Integer)
    bdt1000_type2 = db.Column(db.Integer)
    bdt1000_type3 = db.Column(db.Integer)
    bdt1000_type4 = db.Column(db.Integer)
    bdt1000_retract = db.Column(db.Integer)
    bdt1000_reject = db.Column(db.Integer)
    bdt1000_retract2 = db.Column(db.Integer)
    unknown_type4 = db.Column(db.Integer)
    unknown_retract = db.Column(db.Integer)
    unknown_reject = db.Column(db.Integer)
    unknown_retract2 = db.Column(db.Integer)
    total_abox = db.Column(db.Integer)
    total_type1 = db.Column(db.Integer)
    total_type2 = db.Column(db.Integer)
    total_type3 = db.Column(db.Integer)
    total_type4 = db.Column(db.Integer)
    total_retract = db.Column(db.Integer)
    total_reject = db.Column(db.Integer)
    total_retract2 = db.Column(db.Integer)
    result = db.Column(db.String(100))
    scenario = db.Column(db.String(50))
    retract_type1 = db.Column(db.Integer)
    retract_type2 = db.Column(db.Integer)
    retract_type3 = db.Column(db.Integer)
    retract_type4 = db.Column(db.Integer)
    total_retracted_notes = db.Column(db.Integer)
    deposit_retract_100 = db.Column(db.Integer)
    deposit_retract_500 = db.Column(db.Integer)
    deposit_retract_1000 = db.Column(db.Integer)
    deposit_retract_unknown = db.Column(db.Integer)
    total_deposit_retracted = db.Column(db.Integer)
    file_name = db.Column(db.String(200))
    ej_log = db.Column(db.Text) 